### ISSUE TITLE
Commotion-android  crashes when exiting under certain conditions

### ISSUE THREAD

**Issue by areynold** [opentechinstitute/commotion-android#13]
If the application is connecting to a mesh (and showing Toast notifications about its progress) and the user
1. presses the back button, and
2. clicks the disconnect icon 

the application crashes.

(Was issue 334 on code.commotionwireless.net)

**Comment by areynold** [comment]
Retest to determine if this is still relevant to the cyanogenmod version

**Comment by hawkinswnaf** [comment]
I am closing this because it is no longer relevant with the cm version.
