### ISSUE TITLE
Wrong iconography for android mesh connection error notification

### ISSUE THREAD

**Issue by areynold** [opentechinstitute/commotion-android#14]
The iconography for alerting a user to a failed mesh connection in the notification bar is wrong. It uses the old iconography from the Barnacle app.

(Was issue 335 on code.commotionwireless.net)

**Comment by areynold** [comment]
Retest to determine if this is still relevant in cyanogenmod version

**Comment by hawkinswnaf** [comment]
Corrected in 7d578473b3120c49336414cd595ae0629f9d862b commit to cm branch.
