### ISSUE TITLE
MeshTether Setup BSSID-field accepts numeric only

### ISSUE THREAD

**Issue by areynold** [opentechinstitute/commotion-android#17]
On a number of phones / Android versions, the BSSID field cannot be configured with nonnumeric characters.
Problem occurs on:
- Galaxy Nexus, CM9 (4.0.4) (numeric keyboard)
- Wolfgang AT-AS28D with 2.3.5 (T-9, alphanumeric greyed out)
  On HTC Desire, it worked fine.

Bypass: provide config file or cut&pase

(Was issue 352 on code.commotionwireless.net)

**Comment by hawkinswnaf** [comment]
Fixed in commit fb527906473f13b24593ae6ca24b2d9bd9e26c01 on commotion-android in branch cm on my fork.

**Comment by hawkinswnaf** [comment]
I just pushed my fork of the cm branch to the main OTI repo. This should mean that I can close this issue. I am doing so.
