### ISSUE TITLE
Android makefiles have hardcoded version and tool paths

### ISSUE THREAD

**Issue by areynold** [opentechinstitute/commotion-android#21]
external/Makefile has some hard-coded paths to tools under /opt, causing a build to fail if these paths don't exist. Similar for assumed API v9, when the current as of this writing is v10.

These tool paths and version expectations are not mentioned in the top-level README.md
# Android NDK setup

SDK_BASE ?= /opt/android-sdk
NDK_BASE ?=  /opt/android-ndk
NDK_PLATFORM_LEVEL ?= 9
SDK_PLATFORM_LEVEL ?= 9
NDK_SYSROOT=$(NDK_BASE)/platforms/android-$(NDK_PLATFORM_LEVEL)/arch-arm
SDK_PLATFORM=$(SDK_BASE)/platforms/android-$(SDK_PLATFORM_LEVEL)/
NDK_UNAME := $(shell uname -s | tr '[A-Z]' '[a-z]')
NDK_TOOLCHAIN=$(NDK_BASE)/toolchains/arm-linux-androideabi-4.4.3/prebuilt/$(NDK_UNAME)-x86

Likewise, similar hard-coded paths in these files too:
external/olsrd/make/Makefile.android
external/shell-fork/Makefile.android

(Was issue 458 on code.commotionwireless.net)

**Comment by hawkinswnaf** [comment]
These are not actually hard-coded. They can be specified on the command line. These hard-coded values are simply defaults.

**Comment by hawkinswnaf** [comment]
Updated the README, build.xml and external/Makefile to better document the build process and satisfy this issue. See commit aa6796f4245ccb356ca6134201197c7c498561cc.

I am closing this.
