### ISSUE TITLE
Update application icon for Commotion Android

### ISSUE THREAD

**Issue by critzo** [opentechinstitute/commotion-android#30]
Use the small, circular Commotion icon for the Commotion Android application icon, as well as in the top level menu when the app is running.

**Comment by hawkinswnaf** [comment]
Should be fixed in 6cd47dc56a239ec36ca6bc3c612fd8d39a4ac1e1

**Comment by hawkinswnaf** [comment]
Had to rebase. The actual commit is a292dc8a4522faade41d5ab37c9341d0f876bbfe
