### ISSUE TITLE
Create an About page 

### ISSUE THREAD

**Issue by critzo** [opentechinstitute/commotion-android#31]
Create an About page. Use the text below:

About

Commotion is an open-source communication tool that uses mobile phones, computers and other wireless devices to create decentralized mesh networks.

Version:  1.0 Android
License & Privacy Policy 
(link to website: https://commotionwireless.net/about/license-privacy)
Get Help
(link to website: https://commotionwireless.net/docs)
Get Involved
(link to website: https://commotionwireless.net/developer/resources)

**Comment by hawkinswnaf** [comment]
Fixed in 6ffdd8a599e8ed1df56c09077def35b5764c507d

**Comment by hawkinswnaf** [comment]
Check out 818320707699b9f1009d30e89eb7c0170b698a4e.

**Comment by hawkinswnaf** [comment]
Had to rebase. The actual commit is now 1706798ed4ed00fdbe8dc41c1bd8b4a4d2b96708
