### ISSUE TITLE
Use new icon for connecting/disconnecting from a mesh profile

### ISSUE THREAD

**Issue by critzo** [opentechinstitute/commotion-android#33]
The current icon used to connect/disconnect from a mesh network should be replaced. The button will be designed by internal staff, but in general will be greyed out when not connected and HIG compliant pink when connected.

**Comment by hawkinswnaf** [comment]
Icon updated. Functionality getting closer: b591a27a342f0bf8853806b86a4e9f6998603539

**Comment by hawkinswnaf** [comment]
Functionality and icons are ready. See a925a535bfdf59a5c24b8237b9c51c677ce1a4d5

I am going to close!
